version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_management
    ports:
      - "5672:5672" # Comunicação entre os nós e a CLI
      - "15672:15672" # Comunicação com a API de gerenciamento Web
    volumes:
      # Persistência de dados
      - /docker_conf/rabbitmq/data:/var/lib/rabbitmq
      # Exemplo de como usar o volume logs-folder (se necessário)
      # - logs-folder:/var/log/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: 123456
    restart: always

volumes:
  logs-folder:
    driver: local
